title: UlamPinoy Official Website
baseurl: /
permalink: '/:title/'
palette: gray
header:
  has_nav: true
  logo_img: /images/up-logo-type.svg
  menu:
    actions:
      - label: Sign Up
        url: /signup
  title: UlamPinoy
footer:
  content: '&copy; Stackbit. All rights reserved.'
  has_nav: true
  has_social: true
  has_subscribe: true
  links:
    - new_window: true
      text: Made with Stackbit
      url: 'https://www.stackbit.com'
  logo_img: /images/up-logo-type.svg
  nav_title: Company
  social_title: Community
  subscribe_content: Stay up to date with our latest developments.
  subscribe_title: Subscribe
  tagline: SaaS theme by Stackbit
sass:
  indentWidth: 4
  precision: 10
  style: nested
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
